name: Rust Core CI

on:
  push:
    paths:
      - 'core/**'
      - 'cli/**'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'core/**'
      - 'cli/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: core
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Check workspace
        run: cargo check --workspace
      - name: Test core crates
        run: cargo test -p agent -p ipc -p providers -p actions -p plugins
      - name: CLI help
        run: cargo run -p cli -- --help
