name: Rust Core CI

on:
  push:
    paths:
      - 'core/**'
      - 'cli/**'
      - 'ci/github-actions/**'
  pull_request:
    paths:
      - 'core/**'
      - 'cli/**'

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: core
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Check workspace
        run: cargo check --workspace
      - name: Build CLI
        run: cargo build -p cli
      - name: Test workspace
        run: cargo test --workspace
      - name: Test core crates
        run: cargo test -p agent -p ipc -p providers -p actions -p plugins
      - name: CLI help
        run: cargo run -p cli -- --help
